citysense:
  token_url: "https://citysens.exxcellent.de/management-api/oauth2/token"

  username: ""
  password: ""

  base_url: "https://citysens.exxcellent.de/api/datasets/"

  endpoints:
    air_quality: airquality
    co2: elsysvalues
    door: elsysvalues
    electricity: action_button
    energy: swuheatmetervalues
    feedback_button: action_button
    flood_data: hochwasser
    ground_humidity: bodenfeuchte
    parking_duration: swuparkingvalues/parkingDurationAverage
    parking_events: swuparkingvalues/parkingEvents
    parking_history: swuparkingvalues/parkingOccupationAverage
    parking_state: swuparkingvalues
    person_count: besucherstrom
    raised_garden: loraparkhochbeet
    sound_sensor: lautstaerke
    structure_damage: risssensor
    waste_level: swufillvalues
    weather_station: weatherstation

  pull_interval: 60

sensors:
  sensors_file: sensors.yaml
  model_directory: models
#   :
#     - "elsyselt-a81758fffe04c61f"
#   door:
#     - "elsysems-a81758fffe04887a"
#   weather_station:
#     - "davis-013d4d"
#   feedback_button:
#     - "sa000805-70b3d53260008600"
#   person_count:
#     - "ttgo-paxcounter01"
#   sound_sensor:
#     - "iotsoundsensor-deadbeef13374326"
#   flood_data:
#     - "ultrasonic1"
#     - "ultrasonic2"
#   raised_garden:
#     - "node1"
#   :
#     - "node2"
#   :
#     - "node3abp"
#   :
#     - "node4"
#   :
#     - "sensor000"
#   structure_damage:
#     - "feather01"
#   air_quality:
#     - "dl-ac-001-70b3d57ba0000fc9"
#   ground_humidity:
#     - "soil_283d7a28b8ee0567"
#   waste_level:
#     - "71191"
#   co2:
#     - "elsysco2-045184"
#     - "elsysco2-048e67"
#   energy:
#     - "70113173"
#     - "000003"

rest:
  debug: true

rules:
  rules_directory: rules
