citysense:
  token_url: "https://citysens.exxcellent.de/management-api/oauth2/token"

  username: ""
  password: ""

  base_url: "https://citysens.exxcellent.de/api/datasets/"

  endpoints:
    air_quality: airquality
    co2: elsysvalues
    door: elsysvalues
    electricity: action_button
    energy: swuheatmetervalues
    feedback_button: action_button
    flood_data: hochwasser
    ground_humidity: bodenfeuchte
    parking_duration: swuparkingvalues/parkingDurationAverage
    parking_events: swuparkingvalues/parkingEvents
    parking_history: swuparkingvalues/parkingOccupationAverage
    parking_state: swuparkingvalues
    person_count: besucherstrom
    raised_garden: loraparkhochbeet
    sound_sensor: lautstaerke
    structure_damage: risssensor
    waste_level: swufillvalues
    weather_station: weatherstation

  pull_interval: 60

sensors:
  sensors_file: sensors.yaml
  model_directory: models

rest:
  debug: true

rules:
  rules_directory: rules
